language: rust
rust:
- stable
- beta
- nightly
sudo: false
os:
- linux
cache:
  directories:
  - "$HOME/.cargo"
  - target
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
env:
  matrix:
  - CARGO_FEATURES=
  - CARGO_FEATURES=with-tokio
  - CARGO_FEATURES=with-serde
  global:
  - CARGO_QUIET=
  - CARGO_INCREMENTAL=0
  - secure: qBK47Fr4TKtsNjjuOw1jibuxCMIHWoLorCeTd66xT0xjKvMLoWHV7ygHnPAYHgUQAT83Y+a+FIWRpZWg6HxoBzjW8J46BYDZBevZCjvSQudDy9UCUmtKlcrvwh9Hp7JIc07cANOpVkJnFH5wrHlwfmpBOgykn6wOWdyUK7rrXfU6F9CbslJ1sLRufzoTebfqk4bjtCaa4a6D4xRqpz9t2y1dtBTN8NWpq+zngIlgT/JA+PNppBy/Lsw8e/Z1rHbjBX+Ie1fUXImWQjdmXh47K8ItO/9IghfJsz2CK07OgsjvUrmq5iJXdx5ZTptrvmr2u+4XUYNqVnzlAMxIVF4RCVc0AZvs3ywXZwVWKzTR/Sx9qgCFUVv2nge1xlarK0XbGGfePGWHiBMXAYvSoRn5DVJENEsTql0Hm1PgzwLK79o1WIRwfNuQ5BjlMfb1tsZzp8kspsiynyFTy43Nb0Kx+zj7OXgl67d0EyTCiDPaVBSE6EJrhU3DxoGpNBQaaklFWc7/9exVuWHJKDC3QX81DDM3ehmTKh6BYAHRXUp+SnRgPB2xkpmNqeytaBTKnnRWZnUEnx0Ilz5SL1DVnreyKCT8ahf4TnqTYMB24/WmByTPod4niOvqT5ZlIFA/+aspI9yI7z3wZk7KCh/ygUxh108+tBYmUXhD+Bp86t7DGMQ=
  - secure: lMRhjv6ks6r5WIJbvM38z7vJ4uCKp2uAYMYPi4yXAnJFQgAz2WOxkq3unFJ0XvZHbkvPccEGAwhVVoBPGZPxZk4Xcj4bgqeFEcx5zkNJyAxyOqg4LUC1nNjBGCMmuWqECF/19eC5BlhgIpNWryR/oiWiR7/4cYUWVuhEzg4AcCBC/87UoiHYER7pb9jbp0tRtFnS4GcosCn+fp4w0taFWsRym01THlZikhimvyRpp00SS9JFv8Kiq3UlN851cuKYxxVnTZQQkdkQHErUOm+rgnpc5341vQVcG/1hapjwYCnGxm0iae2Iqd5WzeSCOAO1Suj9zKzAy+QWPoV00IJd3UjsJ411DdTOzGsLtShOopENBDqfrKFBbemKOu+bTWxKsn3U/CQjptoU21PNhppsd6xpjEtrEv5UXJj1rMi7L5DDeP1BkkpFgFrTXwhxsMy6m4/zPkRJoiT4NAkp2Ubx/CxK7b1a1xOfeGdW21bvFxAEt2qrGYdLrc3vdcEoKoebxmybcVfpXKDnELIAJ2yeB6jfGMjt6X5KSj6l3szFMtVdr0mDpbZqiJeyyd8TYvZez2m36e95Fnej+dutncQroZEbA0nnJtSFhfFBoRwrVA3kLLMLrP5YnwsiPPhTDt2MkIWx/8ngXiMWk3+TP1AbGn8Fuzjw4xgOoCcrHRWvlj4=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.1.tar.gz | tar -xzC $HOME && . $HOME/ci-0.1/src
script:
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable && $CARGO_FEATURES = with-serde"
before_deploy:
- cargo doc
- cargo package
after_deploy:
- cargo pages-publish
- cargo publish
