[package]
name = "input-linux"
version = "0.0.1"
authors = ["arcnmx"]

description = "evdev and uinput"
keywords = ["evdev", "uinput", "linux", "input"]

documentation = "http://arcnmx.github.io/input-linux-rs/input_linux"
repository = "https://github.com/arcnmx/input-linux-rs"
readme = "README.md"
license = "MIT"

[dependencies]
input-linux-sys = "^0.3.0"
nix = "^0.10.0"
tokio-io = { version = "^0.1.5", optional = true }
bytes = { version = "^0.4.0", optional = true }

[features]
tokio = ["tokio-io", "bytes"]
